# Generated by Django 2.1.1 on 2018-12-11 17:20

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(blank=True, max_length=100)),
                ('orcid', models.CharField(max_length=100)),
                ('research_group', models.URLField(blank=True, max_length=30)),
                ('linked_in', models.URLField(blank=True, max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('subreddits', models.CharField(blank=True, max_length=512)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('about_me', models.CharField(blank=True, max_length=300)),
                ('tweet_ammount', models.IntegerField(blank=True, default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('show_reddit', models.BooleanField(blank=True, default=True)),
                ('show_twitter', models.BooleanField(blank=True, default=True)),
                ('twitter_account', models.CharField(blank=True, max_length=100)),
                ('reddit_account', models.CharField(blank=True, max_length=100)),
                ('reddit_token', models.CharField(blank=True, max_length=256)),
                ('tweet_request_token', models.CharField(blank=True, max_length=300)),
                ('tweet_access_token', models.CharField(blank=True, max_length=300)),
                ('tweet_access_token_secret', models.CharField(blank=True, max_length=300)),
                ('orcid_token', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
