# Generated by Django 2.1.2 on 2018-10-19 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(blank=True, max_length=30)),
                ('facebook', models.URLField(blank=True, max_length=256)),
                ('linked_in', models.URLField(blank=True, max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('orcid', models.CharField(blank=True, max_length=19)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
