# Generated by Django 2.1.3 on 2018-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subreddits',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
