# Generated by Django 2.1.1 on 2018-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reasearch_group',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
