# Generated by Django 2.1.3 on 2018-11-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_subreddits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reddit_token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
