# Generated by Django 2.1.1 on 2018-11-07 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_tweet_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tweet_access_token',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='tweet_access_token_secret',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='tweet_request_token',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tweet_ammount',
            field=models.IntegerField(blank=True, default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
