# Generated by Django 2.1.1 on 2018-12-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181204_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reasearch_group',
            new_name='research_group',
        ),
    ]
