# Generated by Django 2.1.2 on 2018-11-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181107_2223'),
        ('user', '0003_profile_reddit_token'),
    ]

    operations = [
    ]
