# Generated by Django 2.1.1 on 2018-12-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181204_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orcid',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='research_group',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
