# Generated by Django 2.1.2 on 2018-11-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20181112_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_reddit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_twitter',
            field=models.BooleanField(default=True),
        ),
    ]
