# Generated by Django 2.1.1 on 2018-11-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20181112_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_account',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
