# Generated by Django 2.1.1 on 2018-12-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181210_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research_group',
            field=models.URLField(blank=True, max_length=30),
        ),
    ]
