# Generated by Django 2.1.2 on 2018-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181113_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_reddit',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_twitter',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
