# Generated by Django 2.1.1 on 2018-11-07 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_feed', '0002_auto_20181106_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pubdate'],
                'permissions': (('can_change_status', 'Can see and change articles'),),
            },
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='bookmarks',
            field=models.ManyToManyField(related_name='hashtags', to='news_feed.Bookmark'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='user',
            field=models.ManyToManyField(related_name='interests', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(to='news_feed.Hashtag'),
        ),
        migrations.AddField(
            model_name='post',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
