# Generated by Django 2.1.2 on 2018-11-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0003_auto_20181107_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='person',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='news_feed.Bookmark'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='interests', to='user.Profile'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
