# Generated by Django 2.1.1 on 2018-10-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interests',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
