# Generated by Django 2.1.1 on 2018-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180928_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
